#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c "
        /usr/sbin/nft -f /etc/sing-box/singbox.nft || echo 'Failed to load singbox.nft' >> /tmp/nft_error.log
    "
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}
